### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by kellyselden** [piuccio/rollup-plugin-amd#14]
Do you mind releasing a new version with https://github.com/piuccio/rollup-plugin-amd/pull/13?

**Comment by piuccio** [comment]
Sure, #13 broke the build on node 4, I've opened #15 to fix that. A release is coming soon

**Comment by piuccio** [comment]
Version `3.0.0` is out

**Comment by kellyselden** [comment]
Oh shoot. I won't be able to use that version, as my minimum supported node version for my library (ember-cli) is node 4 until it is end of life.

**Comment by piuccio** [comment]
3 more months 😁
I'm happy to release another version if you make amd-to-es6 work on node 4

**Comment by kellyselden** [comment]
I'll send a friendly nudge.

**Comment by kellyselden** [comment]
node 4 back in version 0.12.1

**Comment by piuccio** [comment]
Oh good, I'll release a new version after the weekend
